### ISSUE TITLE
app or package ?

### ISSUE THREAD

**Issue by shtefcs** [ethereum/meteor-dapp-whisper-chat-client#14]
Hi there,

Is this app or package for meteor ? When  i tried to start as app, i get this message 
![console](http://content.screencast.com/users/shtefcs/folders/Jing/media/a0bb1c6a-842e-459b-925a-8ba36f1d0130/2015-03-01_0730.png)

**Comment by maran** [comment]
Please cd into the app folder and try again. (`cd ~/meteor-dapp-whisper-chat-client/app`)

**Comment by shtefcs** [comment]
oki, its working now
